export {
  paginatedSchema,
  campaignSchema,
  campaignDetailSchema,
  campaignListParamsSchema,
  campaignViewersSchema,
  campaignApplySchema,
  campaignLikesAnalysisSchema,
  campaignLikeSchema,
  type Campaign,
  type CampaignDetail,
  type CampaignImage,
  type CampaignLocation,
  type CampaignDetailInfo,
  type CampaignListParams,
  type CampaignViewers,
  type CampaignApply,
  type CampaignLikesAnalysis,
  type CampaignLike,
  type Paginated,
} from './model/campaign.schema'
export {
  CampaignCategory,
  CampaignType,
  CampaignChannel,
  CampaignStatus,
  CampaignSort,
  CampaignPlatform,
} from './model/campaign.enums'
