import type { Campaign } from '@/entities/campaign'

import type { CreatorPost, HeroSlide } from './home.types'

export const heroSlides: HeroSlide[] = [
  {
    title: '내 블로그 진단하고 더 정확한 공고 추천받기',
    description: 'AI가 내 블로그를 분석하여 상황에 딱 맞는 체험단을 추천해드려요.',
    cta: 'AI 맞춤 체험단 보기 >',
    href: '#ai-campaigns',
  },
  {
    title: '지금 가장 인기 있는 체험단을 확인해보세요',
    description: '수백 개의 체험단 중 지금 가장 많이 신청받고 있는 공고를 모았어요.',
    cta: '인기 체험단 보기 >',
    href: '#popular-campaigns',
  },
  {
    title: '내 근처 체험단, 한눈에 찾아보기',
    description: '지역별로 분류된 체험단을 통해 가까운 공고를 빠르게 찾아보세요.',
    cta: '지역별 체험단 보기 >',
    href: '#region-popular-campaigns',
  },
  {
    title: '인기 블로거들의 생생한 체험 후기',
    description: '실제 체험단에 참여한 블로거들의 솔직한 후기를 확인해보세요.',
    cta: '후기 보러가기 >',
    href: '#creator-posts',
  },
  {
    title: '오늘 새로 올라온 체험단 놓치지 마세요',
    description: '매일 업데이트되는 신규 공고를 가장 먼저 확인하고 선정 확률을 높여보세요.',
    cta: '신규 공고 보기 >',
    href: '#popular-campaigns',
  },
]

export const aiCampaigns: (Campaign & { fitLabel: string })[] = [
  {
    id: 1,
    title: '[서울] 샐러드 정기배송 체험단',
    brandName: '프레시테이블',
    category: 'FOOD',
    type: 'DELIVERY',
    channel: 'BLOG',
    providedContent: '샐러드 정기배송 1개월 무료 체험',
    recruitCount: 20,
    applyCount: 12,
    applyEndDate: '2026-06-10',
    isGuaranteed: false,
    thumbnailUrl: null,
    fitLabel: 'AI 확률 92%',
  },
  {
    id: 2,
    title: '[성수] 피부 관리 프로그램',
    brandName: '오브제스킨',
    category: 'BEAUTY',
    type: 'VISIT',
    channel: 'BLOG',
    providedContent: '프리미엄 피부 관리 1회 무료 체험',
    recruitCount: 15,
    applyCount: 8,
    applyEndDate: '2026-06-08',
    isGuaranteed: false,
    thumbnailUrl: null,
    fitLabel: 'AI 확률 88%',
  },
  {
    id: 3,
    title: '[전국] 홈카페 키트 리뷰어',
    brandName: '그린하우스',
    category: 'LIFESTYLE',
    type: 'DELIVERY',
    channel: 'BLOG',
    providedContent: '홈카페 키트 1세트 제공',
    recruitCount: 30,
    applyCount: 19,
    applyEndDate: '2026-06-12',
    isGuaranteed: false,
    thumbnailUrl: null,
    fitLabel: 'AI 확률 84%',
  },
  {
    id: 4,
    title: '[홍대] 프로필 촬영 체험단',
    brandName: '모먼트스튜디오',
    category: 'CULTURE',
    type: 'VISIT',
    channel: 'BLOG',
    providedContent: '프로필 촬영 1회 무료 제공',
    recruitCount: 10,
    applyCount: 5,
    applyEndDate: '2026-06-07',
    isGuaranteed: false,
    thumbnailUrl: null,
    fitLabel: 'AI 확률 81%',
  },
]

export const highChanceCampaigns: Campaign[] = [
  {
    id: 5,
    title: '[마포] 브런치 카페 방문 체험단',
    brandName: '테이블온',
    category: 'FOOD',
    type: 'VISIT',
    channel: 'BLOG',
    providedContent: '브런치 2인 식사 제공',
    recruitCount: 20,
    applyCount: 6,
    applyEndDate: '2026-06-11',
    isGuaranteed: false,
    thumbnailUrl: null,
  },
  {
    id: 6,
    title: '[전국] 섬유 탈취제 리뷰어',
    brandName: '클린데이',
    category: 'LIFESTYLE',
    type: 'DELIVERY',
    channel: 'BLOG',
    providedContent: '섬유 탈취제 2종 세트 제공',
    recruitCount: 40,
    applyCount: 9,
    applyEndDate: '2026-06-14',
    isGuaranteed: false,
    thumbnailUrl: null,
  },
  {
    id: 7,
    title: '[경기] 반려견 간식 체험단',
    brandName: '브라운독',
    category: 'LIFESTYLE',
    type: 'DELIVERY',
    channel: 'BLOG',
    providedContent: '반려견 간식 3종 세트 제공',
    recruitCount: 18,
    applyCount: 4,
    applyEndDate: '2026-06-09',
    isGuaranteed: false,
    thumbnailUrl: null,
  },
  {
    id: 8,
    title: '[전국] 침실 조명 리뷰어',
    brandName: '무드라이트',
    category: 'LIFESTYLE',
    type: 'DELIVERY',
    channel: 'BLOG',
    providedContent: '침실 조명 1개 제공',
    recruitCount: 25,
    applyCount: 7,
    applyEndDate: '2026-06-13',
    isGuaranteed: false,
    thumbnailUrl: null,
  },
  {
    id: 9,
    title: '[강릉] 오션뷰 숙소 체험단',
    brandName: '온더무브',
    category: 'TRAVEL',
    type: 'VISIT',
    channel: 'BLOG',
    providedContent: '오션뷰 숙소 1박 2일 제공',
    recruitCount: 12,
    applyCount: 3,
    applyEndDate: '2026-06-15',
    isGuaranteed: false,
    thumbnailUrl: null,
  },
]

export const recentCampaigns: Campaign[] = [
  { ...aiCampaigns[0], applyEndDate: '2026-06-07' },
  { ...aiCampaigns[1], applyEndDate: '2026-06-12' },
  { ...aiCampaigns[2], applyEndDate: '2026-06-16' },
  { ...aiCampaigns[3], applyEndDate: '2026-06-08' },
]

export const regionPopularCampaigns: Campaign[] = [
  {
    id: 10,
    title: '[한남] 와인 다이닝 방문 체험단',
    brandName: '한남테이블',
    category: 'FOOD',
    type: 'VISIT',
    channel: 'BLOG',
    providedContent: '와인 다이닝 코스 2인 제공',
    recruitCount: 30,
    applyCount: 10,
    applyEndDate: '2026-06-10',
    isGuaranteed: false,
    thumbnailUrl: null,
  },
  {
    id: 11,
    title: '[연남] 디저트 카페 체험단',
    brandName: '연남라운지',
    category: 'FOOD',
    type: 'VISIT',
    channel: 'BLOG',
    providedContent: '디저트 세트 2인 제공',
    recruitCount: 40,
    applyCount: 14,
    applyEndDate: '2026-06-12',
    isGuaranteed: false,
    thumbnailUrl: null,
  },
  {
    id: 12,
    title: '[부산] 광안리 숙소 리뷰어',
    brandName: '광안스테이',
    category: 'TRAVEL',
    type: 'VISIT',
    channel: 'BLOG',
    providedContent: '광안리 숙소 1박 2일 제공',
    recruitCount: 16,
    applyCount: 5,
    applyEndDate: '2026-06-14',
    isGuaranteed: false,
    thumbnailUrl: null,
  },
  {
    id: 13,
    title: '[제주] 오름 투어 체험단',
    brandName: '제주오름',
    category: 'TRAVEL',
    type: 'VISIT',
    channel: 'BLOG',
    providedContent: '오름 투어 1인 참가권 제공',
    recruitCount: 20,
    applyCount: 7,
    applyEndDate: '2026-06-11',
    isGuaranteed: false,
    thumbnailUrl: null,
  },
  {
    id: 14,
    title: '[대구] 수제맥주 펍 방문 체험단',
    brandName: '대구브루어리',
    category: 'FOOD',
    type: 'VISIT',
    channel: 'BLOG',
    providedContent: '수제맥주 세트 2인 제공',
    recruitCount: 24,
    applyCount: 8,
    applyEndDate: '2026-06-13',
    isGuaranteed: false,
    thumbnailUrl: null,
  },
  {
    id: 15,
    title: '[인천] 스파 케어 프로그램',
    brandName: '인천포레스트',
    category: 'BEAUTY',
    type: 'VISIT',
    channel: 'BLOG',
    providedContent: '스파 케어 1회 제공',
    recruitCount: 32,
    applyCount: 11,
    applyEndDate: '2026-06-16',
    isGuaranteed: false,
    thumbnailUrl: null,
  },
]

export const popularCampaigns: Campaign[] = [
  ...highChanceCampaigns,
  {
    id: 16,
    title: '[부산] 파스타 다이닝 체험단',
    brandName: '아워키친',
    category: 'FOOD',
    type: 'VISIT',
    channel: 'BLOG',
    providedContent: '파스타 코스 2인 제공',
    recruitCount: 50,
    applyCount: 22,
    applyEndDate: '2026-06-17',
    isGuaranteed: false,
    thumbnailUrl: null,
  },
]

export const creatorPosts: CreatorPost[] = [
  { handle: '@dailyplate', likeCount: 120, title: '성수에서 발견한 조용한 브런치 맛집' },
  { handle: '@moodlog', likeCount: 98, title: '작은 방 분위기를 바꾸는 조명 리뷰' },
]
