import type { CampaignDetail } from '@/entities/campaign'

export const mockCampaignDetail: CampaignDetail = {
  id: 1,
  title: '[서울] 샐러드 정기배송 체험단',
  brandName: '프레시테이블',
  category: 'FOOD',
  type: 'DELIVERY',
  channel: 'BLOG',
  providedContent: '샐러드 정기배송 1개월 무료 체험',
  recruitCount: 20,
  applyCount: 12,
  applyEndDate: '2026-06-30',
  isGuaranteed: false,
  thumbnailUrl: null,
  description:
    '신선한 제철 채소로 만든 샐러드를 매주 2회 정기배송으로 체험하고 솔직한 리뷰를 작성해주세요. 배송부터 맛, 신선도, 포장까지 전반적인 후기를 공유해 주시면 됩니다.',
  regionDepth1: '서울',
  regionDepth2: '마포구',
  applyStartDate: '2026-06-01',
  announceDate: '2026-07-05',
  reviewDeadline: '2026-07-20',
  status: 'ACTIVE',
  sourcePlatform: undefined,
  isLiked: false,
  viewerCount: 342,
}

export const mockCampaignDetails: CampaignDetail[] = [
  mockCampaignDetail,
  {
    id: 2,
    title: '[성수] 피부 관리 프로그램',
    brandName: '오브제스킨',
    category: 'BEAUTY',
    type: 'VISIT',
    channel: 'BLOG',
    providedContent: '프리미엄 피부 관리 1회 무료 체험',
    recruitCount: 15,
    applyCount: 8,
    applyEndDate: '2026-06-20',
    isGuaranteed: false,
    thumbnailUrl: null,
    description:
      '성수동에 위치한 프리미엄 스킨케어 샵에서 맞춤 피부 관리를 받고 체험 후기를 작성해주세요. 방문 경험, 서비스, 피부 개선 효과 등을 솔직하게 리뷰해 주시면 됩니다.',
    regionDepth1: '서울',
    regionDepth2: '성동구',
    applyStartDate: '2026-06-01',
    announceDate: '2026-06-25',
    reviewDeadline: '2026-07-10',
    status: 'ACTIVE',
    sourcePlatform: undefined,
    isLiked: true,
    viewerCount: 218,
  },
  {
    id: 3,
    title: '[전국] 홈카페 키트 리뷰어',
    brandName: '그린하우스',
    category: 'LIFESTYLE',
    type: 'DELIVERY',
    channel: 'BLOG',
    providedContent: '홈카페 키트 1세트 제공',
    recruitCount: 30,
    applyCount: 19,
    applyEndDate: '2026-06-25',
    isGuaranteed: false,
    thumbnailUrl: null,
    description:
      '집에서 카페 분위기를 즐길 수 있는 홈카페 키트를 체험하고 리뷰를 작성해주세요. 제품 구성, 사용법, 맛, 활용도 등을 상세하게 소개해 주시면 됩니다.',
    regionDepth1: null,
    regionDepth2: null,
    applyStartDate: '2026-06-01',
    announceDate: '2026-06-28',
    reviewDeadline: '2026-07-15',
    status: 'ACTIVE',
    sourcePlatform: 'INVIEW',
    isLiked: false,
    viewerCount: 501,
  },
]
